import type { Metadata } from "next";
import {IBM_Plex_Serif, Mona_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const ibmPlexSerif = IBM_Plex_Serif({
  variable : "--font-ibm-plex-serif",
  subsets: ['latin'],
  weight : ['400','500','600','700'],
  display : 'swap'

})

const monaSans = Mona_Sans({
  variable : "--font-mona-sans",
  subsets: ['latin'],
  display : 'swap'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSerif.variable} ${monaSans.variable} antialiased`}
      >
        <ClerkProvider>
        <Toaster/>
        <Navbar/>
        {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
